run:
  timeout: 5m

linters:
  enable:
    - errname
    - exhaustive
    - exportloopref
    - gci
    - goconst
    - godot
    - gofmt
    - makezero
    - unconvert
    - unparam
    - whitespace

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  makezero:
    always: false

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - goconst
