name: Release CLI

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build and publish CLI artifacts
        env:
          COMMIT_SHA1: ${{ github.sha }}
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.ref_name }}
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: make dist publish
